### ISSUE TITLE
Torque-value shredder V2

### ISSUE THREAD

**Issue by BenPetersen12** [ONEARMY/academy#80]
Ahoj!:)
The question is why the torque-value on the "Build"-page for the basic shredder is so high?
It´s confusing when someone is searching for the shredder motor...

Shredder V2: 
*[Academy link](https://community.preciousplastic.com/academy/build/shredder) 
*Value on page: 1100 Nm minimum
*Theoretical value for 2,2kW and 70 U/min: 300Nm (M=P/(2 x Pi x n))
*Theoretical value for 2,2kW and 70 U/min: 409Nm (M=P/(2 x Pi x n))
*Minumum torque value as said in the forums: 300Nm
*Maybe the recommented value should be 300Nm - 500Nm ?

Have a nice day!
Thomas

**Comment by Anze-** [comment]
Hey! Hello Thomas! Sorry for this issue, you are right!

The formula we use for the relationship between RPM, Power and torque is the following:

` Power [kW] = Torque [Nm] * Speed [RPM] / 9.5`
hence we have that
`Torque[Nm]=9.5*Power[kW]/RPM`

This means that (as you said) suggested nominal torque should be between 280Nm and 800Nm (considering low RPM motors could go down to about 30 RPMs).

I'm not sure why 1100 Nm min. torque got there, but most probably that value is the minumum torque strength of the shaft-axle assembly!

We will fix the web page as soon as possible,
thanks for your suggestion.

Alberto Anzellotti,
Shredder Engineer @ PreciosuPlastic

**Comment by BenPetersen12** [comment]
Nice! Thanks!

**Comment by davehakkens** [comment]
thanks for creating the issue @BenPetersen12!
fixed now :)
