### ISSUE TITLE
Mix workspace content is wrong

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/academy#82]
The content of the Mix Workspace is mixed up with the sheetpress. Probably some copy&paste problem. 
https://community.preciousplastic.com/academy/spaces/mix

**Comment by darigovresearch** [comment]
@mattia-io we would be happy to make a pull request to fix the content. Could you be more specific as to which content specifically for the sheetpress should not be on this page?

Or has the content changed since you posted the issue and the issue is no longer relevant?

**Comment by mattia-io** [comment]
@darigovresearch hello.. thanks for looking into it. I actually cleaned all the mistakes in the academy>spaces last week. Should be good now. Thanks for offering to help and if you find more grammar or syntax mistakes make sure to inform us so we can make Precious Plastic ever better. 

I will now close this issue. 
Good day!
